### ISSUE TITLE
how to evaluate with FDFR and ISM

### ISSUE THREAD

**Issue by youyuanyi** [VinAIResearch/Anti-DreamBooth#18]
Thanks for your excellent work! 
I want to evaluate the quality of the generated image using FDFR and ISM metrics. However, there is some bug about the scrip:
`python evaluations/ism_fdfr.py --data_dir <path_to__perturb_image_dir> --emb_dirs <paths_to_id_emb_file>`

what is the --emb_dirs <paths_to_id_emb_file>?

**Comment by youyuanyi** [comment]
When I computaing the emb_file for each person, there is some bugs:
`import numpy as np
import os
from deepface import DeepFace
import argparse


def compute_idx_embedding(paths):
    """
    Compute the embedding of each person given images
    """
    print(paths)
    ave_embedding = 0
    count_file = 0
    for path in paths:
        print(path)
        for file in os.listdir(path):
            if file.endswith(".jpg") or file.endswith(".png"):
                try:
                   count_file += 1
                   embedding_objs = DeepFace.represent(img_path = os.path.join(path, file), model_name="ArcFace", detector_backend="retinaface", align=True)
                   embedding = embedding_objs[0]["embedding"]
                   embedding = np.array(embedding)
                   ave_embedding += embedding
                except:
                    print(">>>>>>> SKIP", file)
    ave_embedding /= count_file
    return ave_embedding


def parse_args():
    parser = argparse.ArgumentParser(description='compute embedding for each person')
    parser.add_argument('--img_dir', type=str, default='../data/47/set_B',  help='path to datadir')
    args = parser.parse_args()
    return args

def main():
    args = parse_args()
    compute_idx_embedding(args.img_dir)
    
if __name__ == '__main__':
    main()`

`../data/47/set_B
.
.
/
d
Traceback (most recent call last):
  File "/home/dell/workspace/Anti-DreamBooth-main/evaluations/compute_idx_emb.py", line 41, in <module>
    main()
  File "/home/dell/workspace/Anti-DreamBooth-main/evaluations/compute_idx_emb.py", line 38, in main
    compute_idx_embedding(args.img_dir)
  File "/home/dell/workspace/Anti-DreamBooth-main/evaluations/compute_idx_emb.py", line 16, in compute_idx_embedding
    for file in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: 'd'

Process finished with exit code 1
`
how to fix it?

**Comment by youyuanyi** [comment]
> Thanks for your excellent work! I want to evaluate the quality of the generated image using FDFR and ISM metrics. However, there is some bug about the scrip: `python evaluations/ism_fdfr.py --data_dir <path_to__perturb_image_dir> --emb_dirs <paths_to_id_emb_file>`
> 
> what is the --emb_dirs <paths_to_id_emb_file>?

When I computaing the emb_file for each person, there is some bugs:
`**import numpy as np
import os
from deepface import DeepFace
import argparse

def compute_idx_embedding(paths):
"""
Compute the embedding of each person given images
"""
print(paths)
ave_embedding = 0
count_file = 0
for path in paths:
print(path)
for file in os.listdir(path):
if file.endswith(".jpg") or file.endswith(".png"):
try:
count_file += 1
embedding_objs = DeepFace.represent(img_path = os.path.join(path, file), model_name="ArcFace", detector_backend="retinaface", align=True)
embedding = embedding_objs[0]["embedding"]
embedding = np.array(embedding)
ave_embedding += embedding
except:
print(">>>>>>> SKIP", file)
ave_embedding /= count_file
return ave_embedding

def parse_args():
parser = argparse.ArgumentParser(description='compute embedding for each person')
parser.add_argument('--img_dir', type=str, default='../data/47/set_B', help='path to datadir')
args = parser.parse_args()
return args

def main():
args = parse_args()
compute_idx_embedding(args.img_dir)

if name == 'main':
main()**`

`**../data/47/set_B
.
.
/
d
Traceback (most recent call last):
File "/home/dell/workspace/Anti-DreamBooth-main/evaluations/compute_idx_emb.py", line 41, in
main()
File "/home/dell/workspace/Anti-DreamBooth-main/evaluations/compute_idx_emb.py", line 38, in main
compute_idx_embedding(args.img_dir)
File "/home/dell/workspace/Anti-DreamBooth-main/evaluations/compute_idx_emb.py", line 16, in compute_idx_embedding
for file in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: 'd'

Process finished with exit code 1**
`
how to fix it?

**Comment by youyuanyi** [comment]
When I was compuating emb_file for each person,here is some bugs:
```
import numpy as np
import os
from deepface import DeepFace
import argparse


def compute_idx_embedding(paths):
    """
    Compute the embedding of each person given images
    """
    print(paths)
    ave_embedding = 0
    count_file = 0
    for path in paths:
        print(path)
        for file in os.listdir(path):
            if file.endswith(".jpg") or file.endswith(".png"):
                try:
                   count_file += 1
                   embedding_objs = DeepFace.represent(img_path = os.path.join(path, file), model_name="ArcFace", detector_backend="retinaface", align=True)
                   embedding = embedding_objs[0]["embedding"]
                   embedding = np.array(embedding)
                   ave_embedding += embedding
                except:
                    print(">>>>>>> SKIP", file)
    ave_embedding /= count_file
    return ave_embedding


def parse_args():
    parser = argparse.ArgumentParser(description='compute embedding for each person')
    parser.add_argument('--img_dir', type=str, default='../data/47/set_B',  help='path to datadir')
    args = parser.parse_args()
    return args

def main():
    args = parse_args()
    compute_idx_embedding(args.img_dir)
    
if __name__ == '__main__':
    main()
```
```

../data/47/set_B
.
.
/
d
Traceback (most recent call last):
  File "/home/dell/Anti-DreamBooth-main/evaluations/compute_idx_emb.py", line 41, in <module>
    main()
  File "/home/dell/Anti-DreamBooth-main/evaluations/compute_idx_emb.py", line 38, in main
    compute_idx_embedding(args.img_dir)
  File "/home/dell/Anti-DreamBooth-main/evaluations/compute_idx_emb.py", line 16, in compute_idx_embedding
    for file in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: 'd'

Process finished with exit code 1
```
How to fix it?
