### ISSUE TITLE
ser_fiq.py mxnet load error

### ISSUE THREAD

**Issue by youyuanyi** [VinAIResearch/Anti-DreamBooth#19]
I have place the insightface-0001.params and insightface-symbol.json in the ./insightface/model, but there is another problem:
```
[16:43:01] C:\Jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:204: Warning: loading symbol saved by MXNet version 10800 with lower version of MXNet v10700. May cause undefined behavior. Please update MXNet if you encounter any issue
E:\Anaconda\envs\fiq\lib\site-packages\mxnet\gluon\block.py:1512: UserWarning: Cannot decide type for the following arguments. Consider providing them as input:
	data: None
  input_sym_arg_type = in_param.infer_type()[0]
Traceback (most recent call last):
  File "E:\Pycharm\Adversarial_Fuxian\eva_exp\evaluations\ser_fiq.py", line 38, in <module>
    fia_score = main()
  File "E:\Pycharm\Adversarial_Fuxian\eva_exp\evaluations\ser_fiq.py", line 18, in main
    ser_fiq = SER_FIQ(gpu=None)
  File "E:\Pycharm\Adversarial_Fuxian\eva_exp\evaluations\FaceImageQuality\face_image_quality.py", line 85, in __init__
    self.detector = mtcnn_detector.MtcnnDetector(model_folder="./FaceImageQuality/insightface/model/",
  File "E:\Pycharm\Adversarial_Fuxian\eva_exp\evaluations\FaceImageQuality\insightface\src\mtcnn_detector.py", line 58, in __init__
    workner_net = mx.model.FeedForward.load(models[0], 1, ctx=ctx)
  File "E:\Anaconda\envs\fiq\lib\site-packages\mxnet\model.py", line 976, in load
    symbol, arg_params, aux_params = load_checkpoint(prefix, epoch)
  File "E:\Anaconda\envs\fiq\lib\site-packages\mxnet\model.py", line 476, in load_checkpoint
    symbol = sym.load('%s-symbol.json' % prefix)
  File "E:\Anaconda\envs\fiq\lib\site-packages\mxnet\symbol\symbol.py", line 2948, in load
    check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
  File "E:\Anaconda\envs\fiq\lib\site-packages\mxnet\base.py", line 246, in check_call
    raise get_last_ffi_error()
mxnet.base.MXNetError: Traceback (most recent call last):
  File "C:\Jenkins\workspace\mxnet-tag\mxnet\3rdparty\dmlc-core\src\io\local_filesys.cc", line 209
LocalFileSystem: Check failed: allow_null: :Open "./FaceImageQuality/insightface/model/det1-symbol.json": No such file or directory

Process finished with exit code 1

```

**Comment by quandao10** [comment]
I met the same problem while running SER-FQA, but on ubuntu. I'm not sure if it is the same on Window. The way I solved that problem is to install the mxnet-cu{xxx} (where xxx is cuda version that match your local machine cuda). Please refer to the website [mxnet]( https://pypi.org/project/mxnet/)
