### ISSUE TITLE
ValueError: value should be one of int, float, str, bool, or torch.Tensor   

### ISSUE THREAD

**Issue by ChelsyHu** [VinAIResearch/Anti-DreamBooth#22]
Help!  a mistake occurs to my program.
I have tried to pip install pytorch.lightning==0.7.3 as other people said online, but it still can't work.
What can I do?    The bug information is as below.     I will thank you very much as someone can help me.

Traceback (most recent call last):
  File "/ssd-sata1/hqq/Anti-DreamBooth/train_dreambooth.py", line 1012, in <module>
    main(args)
  File "/ssd-sata1/hqq/Anti-DreamBooth/train_dreambooth.py", line 852, in main
    accelerator.init_trackers("dreambooth", config=vars(args))
  File "/ssd-sata1/hqq/anaconda3/envs/anti-dreambooth/lib/python3.9/site-packages/accelerate/accelerator.py", line 495, in wrapper
    return func(self, *args, **kwargs)
  File "/ssd-sata1/hqq/anaconda3/envs/anti-dreambooth/lib/python3.9/site-packages/accelerate/accelerator.py", line 1795, in init_trackers
    tracker.store_init_configuration(config)
  File "/ssd-sata1/hqq/anaconda3/envs/anti-dreambooth/lib/python3.9/site-packages/accelerate/tracking.py", line 176, in store_init_configuration
    self.writer.add_hparams(values, metric_dict={})
  File "/ssd-sata1/hqq/anaconda3/envs/anti-dreambooth/lib/python3.9/site-packages/torch/utils/tensorboard/writer.py", line 336, in add_hparams
    exp, ssi, sei = hparams(hparam_dict, metric_dict, hparam_domain_discrete)
  File "/ssd-sata1/hqq/anaconda3/envs/anti-dreambooth/lib/python3.9/site-packages/torch/utils/tensorboard/summary.py", line 231, in hparams
    raise ValueError(
ValueError: value should be one of int, float, str, bool, or torch.Tensor

**Comment by Jingy-Wang** [comment]
pip uninstall tensorboard 意外解决了我这个报错问题
